allowBuilds:
  '@astryxdesign/cli': false
  '@astryxdesign/core': false
  '@parcel/watcher': set this to true or false
  argon2: false
  bufferutil: false
  cpu-features: false
  esbuild: true
  protobufjs: true
  secp256k1: false
  sharp: set this to true or false
  ssh2: false
  unrs-resolver: false
  utf-8-validate: false
